# Support Awesome Buy Me a Coffee pages by using the funding links below
# Developed and maintained by Waren Gonzaga

custom: ['https://warengonzaga.com/donate']

# Your donation means a lot to me to continue the development of open-source project like this.
